# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grPlot = PlotWidget(self.centralwidget)
        self.grPlot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grPlot.sizePolicy().hasHeightForWidth())
        self.grPlot.setSizePolicy(sizePolicy)
        self.grPlot.setBaseSize(QtCore.QSize(1011, 900))
        self.grPlot.setObjectName("grPlot")
        self.verticalLayout_3.addWidget(self.grPlot)
        self.fftPlot = MatplotlibWidget(self.centralwidget)
        self.fftPlot.setObjectName("fftPlot")
        self.verticalLayout_3.addWidget(self.fftPlot)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.manualTextTab = QtWidgets.QWidget()
        self.manualTextTab.setObjectName("manualTextTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.manualTextTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.manualTextTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textConfirmBtn = QtWidgets.QPushButton(self.manualTextTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textConfirmBtn.sizePolicy().hasHeightForWidth())
        self.textConfirmBtn.setSizePolicy(sizePolicy)
        self.textConfirmBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textConfirmBtn.setObjectName("textConfirmBtn")
        self.horizontalLayout_3.addWidget(self.textConfirmBtn)
        self.mRecordBtn = QtWidgets.QPushButton(self.manualTextTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mRecordBtn.sizePolicy().hasHeightForWidth())
        self.mRecordBtn.setSizePolicy(sizePolicy)
        self.mRecordBtn.setObjectName("mRecordBtn")
        self.horizontalLayout_3.addWidget(self.mRecordBtn)
        self.mResetBtn = QtWidgets.QPushButton(self.manualTextTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mResetBtn.sizePolicy().hasHeightForWidth())
        self.mResetBtn.setSizePolicy(sizePolicy)
        self.mResetBtn.setObjectName("mResetBtn")
        self.horizontalLayout_3.addWidget(self.mResetBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.manualTextTab, "")
        self.readBookTab = QtWidgets.QWidget()
        self.readBookTab.setAutoFillBackground(False)
        self.readBookTab.setObjectName("readBookTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.readBookTab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bookText = QtWidgets.QLineEdit(self.readBookTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookText.sizePolicy().hasHeightForWidth())
        self.bookText.setSizePolicy(sizePolicy)
        self.bookText.setObjectName("bookText")
        self.verticalLayout_5.addWidget(self.bookText)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.skipBtn = QtWidgets.QPushButton(self.readBookTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipBtn.sizePolicy().hasHeightForWidth())
        self.skipBtn.setSizePolicy(sizePolicy)
        self.skipBtn.setObjectName("skipBtn")
        self.horizontalLayout_4.addWidget(self.skipBtn)
        self.backBtn = QtWidgets.QPushButton(self.readBookTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_4.addWidget(self.backBtn)
        self.rRecordBtn = QtWidgets.QPushButton(self.readBookTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rRecordBtn.sizePolicy().hasHeightForWidth())
        self.rRecordBtn.setSizePolicy(sizePolicy)
        self.rRecordBtn.setObjectName("rRecordBtn")
        self.horizontalLayout_4.addWidget(self.rRecordBtn)
        self.rResetBtn = QtWidgets.QPushButton(self.readBookTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rResetBtn.sizePolicy().hasHeightForWidth())
        self.rResetBtn.setSizePolicy(sizePolicy)
        self.rResetBtn.setObjectName("rResetBtn")
        self.horizontalLayout_4.addWidget(self.rResetBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.readBookTab, "")
        self.optionsTab = QtWidgets.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.optionsTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usernameInput = QtWidgets.QLineEdit(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameInput.sizePolicy().hasHeightForWidth())
        self.usernameInput.setSizePolicy(sizePolicy)
        self.usernameInput.setObjectName("usernameInput")
        self.gridLayout.addWidget(self.usernameInput, 0, 1, 1, 1)
        self.bookNameInput = QtWidgets.QLineEdit(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookNameInput.sizePolicy().hasHeightForWidth())
        self.bookNameInput.setSizePolicy(sizePolicy)
        self.bookNameInput.setObjectName("bookNameInput")
        self.gridLayout.addWidget(self.bookNameInput, 1, 1, 1, 1)
        self.bookLabel = QtWidgets.QLabel(self.optionsTab)
        self.bookLabel.setObjectName("bookLabel")
        self.gridLayout.addWidget(self.bookLabel, 1, 0, 1, 1)
        self.userLabel = QtWidgets.QLabel(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLabel.sizePolicy().hasHeightForWidth())
        self.userLabel.setSizePolicy(sizePolicy)
        self.userLabel.setObjectName("userLabel")
        self.gridLayout.addWidget(self.userLabel, 0, 0, 1, 1)
        self.opConfirmBtn = QtWidgets.QPushButton(self.optionsTab)
        self.opConfirmBtn.setObjectName("opConfirmBtn")
        self.gridLayout.addWidget(self.opConfirmBtn, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.optionsTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textConfirmBtn.setText(_translate("MainWindow", "Confirm Text"))
        self.mRecordBtn.setText(_translate("MainWindow", "Record"))
        self.mResetBtn.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manualTextTab), _translate("MainWindow", "Manual Text Input"))
        self.skipBtn.setText(_translate("MainWindow", "Skip"))
        self.backBtn.setText(_translate("MainWindow", "Back"))
        self.rRecordBtn.setText(_translate("MainWindow", "Record"))
        self.rResetBtn.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.readBookTab), _translate("MainWindow", "Read Stuff"))
        self.bookLabel.setText(_translate("MainWindow", "Book Name:"))
        self.userLabel.setText(_translate("MainWindow", "User:"))
        self.opConfirmBtn.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("MainWindow", "Options"))

from matplotlibwidget import MatplotlibWidget
from pyqtgraph import PlotWidget
